security:
    encoders:
        Dadamssg\DemoApp\Bundle\UserBundle\Entity\DoctrineUser: sha512
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            anonymous: ~
