Dadamssg\DemoApp\Model\User\Value\EncodedPassword:
    type: embeddable
    fields:
        salt:
            type: string
            length: 255
            column: salt
        password:
            type: string
            length: 255
            column: password