services:
    demo_app.user.register_user_handler:
        class: Dadamssg\DemoApp\Model\User\Handler\RegisterUserHandler
        arguments:
            - @demo_app.user.user_repository
            - @demo_app.user.password_encoder
        tags:
            - { name: command_handler, handles: Dadamssg\DemoApp\Model\User\Command\RegisterUser }