services:
    demo_app.user.send_confirmation_email_listener:
        class: Dadamssg\DemoApp\Model\User\Listener\SendConfirmationEmailListener
        arguments:
            - @demo_app.user.user_repository
            - @demo_app.user.user_mailer
        tags:
            - { name: event_subscriber, subscribes_to:  Dadamssg\DemoApp\Model\User\Event\UserRegistered }