services:
    demo_app.app.validator:
        class: Dadamssg\DemoApp\Bundle\AppBundle\Validator\SymfonyValidator
        arguments:
            - @validator

    demo_app.app.form_error_extractor:
        class: Dadamssg\DemoApp\Bundle\AppBundle\Form\ErrorExtractor