services:
    demo_app.app.doctrine_data_manipulator:
        class: Dadamssg\DemoApp\Bundle\AppBundle\Data\DoctrineDataManipulator
        arguments:
            - @doctrine.orm.entity_manager
            - %database_user%